// <auto-generated />
using System;
using MediaHub.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MediaHub.Data.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20191103150858_AddTestSeed")]
    partial class AddTestSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MediaHub.Model.TestModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("TestName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("TestModels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("36e5edab-25fd-4f69-8957-c3a361857828"),
                            CreateDate = new DateTime(2019, 11, 3, 23, 8, 57, 100, DateTimeKind.Local).AddTicks(6744),
                            TestName = "111"
                        },
                        new
                        {
                            Id = new Guid("96a217af-a13b-471a-947b-0b60a8299980"),
                            CreateDate = new DateTime(2019, 11, 3, 23, 8, 57, 101, DateTimeKind.Local).AddTicks(8699),
                            TestName = "222"
                        },
                        new
                        {
                            Id = new Guid("30ab18f6-bccc-4ced-a7aa-2faee870d5c4"),
                            CreateDate = new DateTime(2019, 11, 3, 23, 8, 57, 101, DateTimeKind.Local).AddTicks(8712),
                            TestName = "333"
                        },
                        new
                        {
                            Id = new Guid("98a1927e-a355-4a0a-af50-3d875fae9973"),
                            CreateDate = new DateTime(2019, 11, 3, 23, 8, 57, 101, DateTimeKind.Local).AddTicks(8715),
                            TestName = "444"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
