// <auto-generated />
using System;
using MediaHub.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MediaHub.Data.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20191111154936_AddFileModel")]
    partial class AddFileModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MediaHub.Model.FileModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("ExtensionName")
                        .IsRequired();

                    b.Property<string>("FileName")
                        .IsRequired();

                    b.Property<string>("FilePath")
                        .IsRequired();

                    b.Property<long>("FileSize");

                    b.HasKey("Id");

                    b.ToTable("FileModels");
                });

            modelBuilder.Entity("MediaHub.Model.TestModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("TestName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("TestModels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ad6360b1-038f-44c4-8396-075ef9fd6d56"),
                            CreateDate = new DateTime(2019, 11, 11, 23, 49, 35, 379, DateTimeKind.Local).AddTicks(2264),
                            TestName = "111"
                        },
                        new
                        {
                            Id = new Guid("008c115b-814d-4f18-8f21-0c74df5e4475"),
                            CreateDate = new DateTime(2019, 11, 11, 23, 49, 35, 380, DateTimeKind.Local).AddTicks(5027),
                            TestName = "222"
                        },
                        new
                        {
                            Id = new Guid("3e59ef98-3eb3-4df4-a384-88e3d1125665"),
                            CreateDate = new DateTime(2019, 11, 11, 23, 49, 35, 380, DateTimeKind.Local).AddTicks(5092),
                            TestName = "333"
                        },
                        new
                        {
                            Id = new Guid("91d079d8-705e-4a6a-b50d-661e711b0a0f"),
                            CreateDate = new DateTime(2019, 11, 11, 23, 49, 35, 380, DateTimeKind.Local).AddTicks(5095),
                            TestName = "444"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
